lab-1-heapsort initial commit
leadpogrommer/OOP pull request #1
Opened 2021-09-23 16:23 UTC by leadpogrommer

2021-09-23 17:17 UTC, molo4evan commented on Task_1_1_1/src/main/java/HeapSorter.java
> +        while (true){
Ну здесь `break` внутри цикла как-то не особенно оправдан, давай попробуем все-таки без `while(true)`

2021-09-23 17:17 UTC, molo4evan commented on Task_1_1_1/src/main/java/HeapSorter.java
> +        for(int i = arr.length - 1; i >= 0; i-- ) heapify(arr, i, arr.length);
А нам точно нужно обходить весь массив? Нельзя ли как-то сократить проход?

2021-09-23 17:17 UTC, molo4evan commented on Task_1_1_1/src/main/java/HeapSorter.java
> +            int tmp = arr[0];
Вынести дублирующийся код в метод (дубликат: строки 17-19)

2021-09-23 17:17 UTC, molo4evan commented on Task_1_1_1/src/test/java/HeapSorterTest.java
> +        Random rnd = new Random(2281337);
Вынести в `@BeforeAll`

2021-09-23 17:17 UTC, molo4evan commented on Task_1_1_1/src/test/java/HeapSorterTest.java
> +        for (int i = 0; i < 10; i++){
По сути, у тебя тут 10 тестов в 1

Попробуй переделать через `@ParameterizedTest`

2021-09-23 17:17 UTC, molo4evan commented on Task_1_1_1/src/test/java/HeapSorterTest.java
> +class HeapSorterTest {
А как насчет краевых случаев? Пустой массив, `null`, может быть, еще что-то?

2021-09-23 17:21 UTC, molo4evan commented on Task_1_1_1/src/main/java/HeapSorter.java
> +public class HeapSorter {
Сделай вменяемую структуру пакетов, без складывания классов в корень

Я упоминал об этом на паре

Для тестов тоже хороший тон - такой же базовый пакет, что и для основного кода

2021-09-24 08:25 UTC, leadpogrommer commented on Task_1_1_1/src/main/java/HeapSorter.java
> +            int tmp = arr[0];
Я не вижу дубликата

2021-09-24 10:32 UTC, molo4evan requested changes

2021-09-24 10:32 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/leadpogrommer/oop/heapsort/HeapSorter.java
> +        while (!done) {
Уже почти, но теперь хочу, чтобы никаких доп переменных не было, а условие выхода опиралось на состояние внутри цикла непосредственно

(Подсказка: `do-while` - твой бро)

2021-09-25 07:31 UTC, leadpogrommer commented on Task_1_1_1/src/main/java/ru/leadpogrommer/oop/heapsort/HeapSorter.java
> +        while (!done) {
done

2021-09-27 17:24 UTC, molo4evan requested changes

2021-09-27 17:24 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/leadpogrommer/oop/heapsort/HeapSorter.java
> +        }while(largest != i);
Пробелы хочу

2021-09-27 17:24 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/leadpogrommer/oop/heapsort/HeapSorter.java
> +            i = largest;
Java позволяет переприсваивать значение параметров метода, но это очень плохая практика (на предыдущей итерации ревью не заметил, прошу прощения). 

Хочешь менять `i` внутри метода - создай локальную переменную.

2021-09-29 05:42 UTC, leadpogrommer commented on Task_1_1_1/src/main/java/ru/leadpogrommer/oop/heapsort/HeapSorter.java
> +            i = largest;
ok

2021-09-29 05:42 UTC, leadpogrommer commented on Task_1_1_1/src/main/java/ru/leadpogrommer/oop/heapsort/HeapSorter.java
> +        }while(largest != i);
ok

2021-09-29 18:11 UTC, merged