lab-1-find initial commit
leadpogrommer/OOP pull request #2
Opened 2021-09-23 16:58 UTC by leadpogrommer

2021-09-24 16:39 UTC, molo4evan requested changes

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +        while (true) {
Тоже предлагаю придумать вариант без бесконечного цикла с `break`

https://stackoverflow.com/questions/390481/is-while-true-with-break-bad-programming-practice

`while(true)` оправдан, если у тебя есть код, который выполняется потенциально бесконечно, в противном случае это сильно ухудшает читаемость.

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +     * @throws IOException Because IDEA wants me to write 'throws'
Не "потому что заставила", а когда может бросить-то? Эксепшн летит из-за того, что IDEA заставила?

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +     * @param filepath Path to the file where we should search for strinf
Очепятка

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +            var nextChar = file.read();
Вообще, формально здесь нет ошибки, но читать из файла посимвольно - **очень** плохая практика. А `FileReader` именно это и делает.

Руками буферизацию реализовывать не обязательно, есть `BufferedReader`.

https://www.geeksforgeeks.org/difference-between-bufferedreader-and-filereader-in-java/

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +            if (nextChar == -1) break;
Ну не, наивный алгоритм - слишком скучно, хотелось бы что-то поэффективнее, например, с эвристикой выбора стоп-символа. Советую посмотреть на алгоритмы поиска подстроки на той же википедии, от себя советую, например, Ахо-Корасика, Бойера-Мура или Рабина-Карпа, они довольно-таки хрестоматийные.

Правда, тут уже `nextChar()` обойтись не получится.

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +     * Helper function because JUnit cannot compare collections
JUnit cannot, а AssertJ can, покопайся там

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +    public static ArrayList<Integer> findSubstring(String filepath, String substring) throws IOException {
Возвращать здесь можно просто `List`, чтобы не парить юзеру мозг реализацией коллекции

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +        var file = new FileReader(filepath);
**Проверки параметров**

По сути, это библиотека, извне могут подать все, что угодно

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +     * @throws IOException Because IDEA
Because IDEA не канает

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +    void findSubstring() throws IOException {
Лучше параметризованным тестом

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +        t.deleteOnExit();
Имеет смысл вынести чистку в `AfterAll` (например, в `BeforeAll` создаем `tmp` директорию, в `AfterAll` рекурсивно сносим ее)

2021-09-24 16:39 UTC, molo4evan commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +        writer.close();
См. `try-with-resources`

2021-09-24 17:28 UTC, molo4evan commented on Task_1_1_2/src/main/java/StringFinder.java
> +                substrPos = 0;
Этот алгоритм сможет найти `aabb` в `aaabb`?

2021-09-25 07:35 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +     * @param filepath Path to the file where we should search for strinf
fixed

2021-10-01 08:08 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +                substrPos = 0;
ok

2021-10-01 08:09 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +            if (nextChar == -1) break;
ok

2021-10-01 08:09 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +            var nextChar = file.read();
ok

2021-10-01 08:43 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +        while (true) {
ok

2021-10-01 08:43 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +     * @throws IOException Because IDEA wants me to write 'throws'
ok

2021-10-01 08:43 UTC, leadpogrommer commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +     * Helper function because JUnit cannot compare collections
not needed

2021-10-01 08:44 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +    public static ArrayList<Integer> findSubstring(String filepath, String substring) throws IOException {
ok

2021-10-01 08:46 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/StringFinder.java
> +        var file = new FileReader(filepath);
ok

2021-10-01 08:47 UTC, leadpogrommer commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +     * @throws IOException Because IDEA
ok

2021-10-01 08:47 UTC, leadpogrommer commented on Task_1_1_2/src/test/java/StringFinderTest.java
> +    void findSubstring() throws IOException {
ok

2021-10-08 06:29 UTC, molo4evan commented on Task_1_1_2/src/test/java/ru/leadpogrommer/oop/stringfinder/StringFinderTest.java
> +        var rdr = new StringReader(haystack);
Сделай ParameterizedTest на те же кейсы, что и с файлом

2021-10-08 06:29 UTC, molo4evan commented on Task_1_1_2/src/main/java/ru/leadpogrommer/oop/stringfinder/StringFinder.java
> +        for (int j = 1, maxZidx = 0, maxZ = 0; j < m; j++) {
Объявляя в for что-то кроме индекса, ты затрудняешь чтение кода

2021-10-08 06:51 UTC, leadpogrommer commented on Task_1_1_2/src/main/java/ru/leadpogrommer/oop/stringfinder/StringFinder.java
> +        for (int j = 1, maxZidx = 0, maxZ = 0; j < m; j++) {
ok

2021-10-08 07:45 UTC, molo4evan approved these changes

2021-10-08 07:46 UTC, merged